{% set name = "pytest-pythonpath" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-pythonpath-{{ version }}.tar.gz
  sha256: 64e195b23a8f8c0c631fb16882d9ad6fa4137ed1f2961ddd15d52065cd435db6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <4.0
    - pip
  run:
    - python <4.0
    - pytest >=2.5.2,<7

test:
  imports:
    - pytest_pythonpath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bigsassy/pytest-pythonpath
  summary: pytest plugin for adding to the PYTHONPATH from command line or configs.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
